apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ai-task-manager.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.postgres.credentials.database }}
  NEXT_PUBLIC_API_URL: {{ .Values.frontend.env.apiUrl }}
