apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ai-task-manager.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.credentials.user }}
  POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password }}
  DATABASE_URL: {{ include "ai-task-manager.databaseUrl" . }}
  GROQ_API_KEY: {{ .Values.backend.env.groqApiKey | quote }}